// Generated by CoffeeScript 1.6.2
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Hello World!'
    });
  };

  exports["super"] = function(req, res) {
    return res.render('super', {
      title: 'super shapes'
    });
  };

}).call(this);
