// Generated by CoffeeScript 1.6.2
(function() {
  var app, cvCss, cvJs, piler, srv,
    __slice = [].slice;

  app = null;

  srv = null;

  piler = null;

  cvJs = null;

  cvCss = null;

  exports.initialize = function(_app, _srv, _piler) {
    app = _app;
    srv = _srv;
    piler = _piler;
    cvJs = piler.createJSManager();
    cvJs.renderTagsDefer = function() {
      var namespaces, src, tags, _i, _len, _ref;

      namespaces = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      tags = "";
      _ref = this.getSources.apply(this, namespaces);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        src = _ref[_i];
        tags += this.wrapInTag(src[0], 'defer="defer"' + (src[1] || ''));
        tags += "\n";
      }
      return tags;
    };
    cvJs.bind(app, srv);
    ['jquery2.js', 'd3.js', 'superformula.js', 'underscore.js'].forEach(function(f) {
      return cvJs.addFile("libs", "public/javascript/libs/" + f);
    });
    cvCss = piler.createCSSManager();
    cvCss.bind(app, srv);
    cvCss.addFile("cv", "public/styles/fx.styl");
    cvCss.addFile("home", "public/styles/home.styl");
    ['libs/d3.js', 'home.coffee'].forEach(function(f) {
      return cvJs.addFile("home", "public/javascript/" + f);
    });
    return this;
  };

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Homam Hosseini',
      js: cvJs,
      css: cvCss
    });
  };

  exports.cv = function(req, res) {
    return res.render('cv', {
      title: 'Homam Hosseini',
      js: cvJs,
      css: cvCss,
      ed: true
    });
  };

  exports["super"] = function(req, res) {
    return res.render('super', {
      title: 'super shapes',
      css: cvCss,
      js: cvJs
    });
  };

}).call(this);
